QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++11

# The following define makes your compiler emit warnings if you use
# any Qt feature that has been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    main.cpp \
    mainwindow.cpp

HEADERS += \
    mainwindow.h

FORMS += \
    mainwindow.ui

TRANSLATIONS += \
    OpensimQtGUI_en_US.ts

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

DISTFILES += \
    Images/DefaultIcon/3D-Cube.png \
    Images/DefaultIcon/3D-Y-Axis-Rotation.png \
    Images/DefaultIcon/3D-Z-Axis-Rotation.png \
    Images/DefaultIcon/3D-cylinder.png \
    Images/DefaultIcon/3D-glasses.png \
    Images/DefaultIcon/3D-plane.png \
    Images/DefaultIcon/3D-pyramid.png \
    Images/DefaultIcon/3D-sphere.png \
    Images/DefaultIcon/3D-wedge.png \
    Images/DefaultIcon/3D_X_Axis_Rotation.png \
    Images/DefaultIcon/4-direction-alt.png \
    Images/DefaultIcon/4-direction.png \
    Images/DefaultIcon/8-direction-alt.png \
    Images/DefaultIcon/8-direction.png \
    Images/DefaultIcon/MD-analog.png \
    Images/DefaultIcon/MD-aspect-ratio-alt.png \
    Images/DefaultIcon/MD-aspect-ratio.png \
    Images/DefaultIcon/MD-audio.png \
    Images/DefaultIcon/MD-backward.png \
    Images/DefaultIcon/MD-betamax.png \
    Images/DefaultIcon/MD-brightness.png \
    Images/DefaultIcon/MD-camera-photo-alt-1.png \
    Images/DefaultIcon/MD-camera-photo-alt-2.png \
    Images/DefaultIcon/MD-camera-photo-alt-3.png \
    Images/DefaultIcon/MD-camera-photo.png \
    Images/DefaultIcon/MD-camera-polaroid.png \
    Images/DefaultIcon/MD-camera-surveillance.png \
    Images/DefaultIcon/MD-camera-video-alt-1.png \
    Images/DefaultIcon/MD-camera-video-alt-2.png \
    Images/DefaultIcon/MD-camera-video.png \
    Images/DefaultIcon/MD-camera-web.png \
    Images/DefaultIcon/MD-cassette-tape.png \
    Images/DefaultIcon/MD-cd-burn.png \
    Images/DefaultIcon/MD-cd-card.png \
    Images/DefaultIcon/MD-cd.png \
    Images/DefaultIcon/MD-contrast.png \
    Images/DefaultIcon/MD-dat.png \
    Images/DefaultIcon/MD-disc-3''.png \
    Images/DefaultIcon/MD-disc-3-5''.png \
    Images/DefaultIcon/MD-disc-5-1-4''.png \
    Images/DefaultIcon/MD-eject.png \
    Images/DefaultIcon/MD-equalizer-alt.png \
    Images/DefaultIcon/MD-equalizer.png \
    Images/DefaultIcon/MD-fast-backward-alt.png \
    Images/DefaultIcon/MD-fast-backward.png \
    Images/DefaultIcon/MD-fast-forward-alt.png \
    Images/DefaultIcon/MD-fast-forward.png \
    Images/DefaultIcon/MD-film.png \
    Images/DefaultIcon/MD-flash.png \
    Images/DefaultIcon/MD-headphones-alt.png \
    Images/DefaultIcon/MD-headphones-mic.png \
    Images/DefaultIcon/MD-headphones.png \
    Images/DefaultIcon/MD-inverse.png \
    Images/DefaultIcon/MD-knob-alt.png \
    Images/DefaultIcon/MD-knob-decrease.png \
    Images/DefaultIcon/MD-knob-increase.png \
    Images/DefaultIcon/MD-knob-volume.png \
    Images/DefaultIcon/MD-knob.png \
    Images/DefaultIcon/MD-levels-alt.png \
    Images/DefaultIcon/MD-levels-decrease.png \
    Images/DefaultIcon/MD-levels-increase.png \
    Images/DefaultIcon/MD-levels.png \
    Images/DefaultIcon/MD-microphone-alt.png \
    Images/DefaultIcon/MD-microphone.png \
    Images/DefaultIcon/MD-minidisc.png \
    Images/DefaultIcon/MD-music.png \
    Images/DefaultIcon/MD-next.png \
    Images/DefaultIcon/MD-pause.png \
    Images/DefaultIcon/MD-photo-alt 2.png \
    Images/DefaultIcon/MD-photo-alt-1.png \
    Images/DefaultIcon/MD-photo.png \
    Images/DefaultIcon/MD-photos-alt.png \
    Images/DefaultIcon/MD-photos.png \
    Images/DefaultIcon/MD-picture-broken-link-alt.png \
    Images/DefaultIcon/MD-picture-broken-link.png \
    Images/DefaultIcon/MD-play.png \
    Images/DefaultIcon/MD-previous.png \
    Images/DefaultIcon/MD-radio.png \
    Images/DefaultIcon/MD-record.png \
    Images/DefaultIcon/MD-reload.png \
    Images/DefaultIcon/MD-repeat-alt.png \
    Images/DefaultIcon/MD-repeat-once.png \
    Images/DefaultIcon/MD-repeat.png \
    Images/DefaultIcon/MD-resume.png \
    Images/DefaultIcon/MD-shuffle.png \
    Images/DefaultIcon/MD-sound.png \
    Images/DefaultIcon/MD-speaker-alt.png \
    Images/DefaultIcon/MD-speaker.png \
    Images/DefaultIcon/MD-split.png \
    Images/DefaultIcon/MD-stop.png \
    Images/DefaultIcon/MD-stream-audio.png \
    Images/DefaultIcon/MD-stream-video.png \
    Images/DefaultIcon/MD-synth.png \
    Images/DefaultIcon/MD-time-pos-back.png \
    Images/DefaultIcon/MD-time-pos-forward.png \
    Images/DefaultIcon/MD-time-pos-set.png \
    Images/DefaultIcon/MD-time-position.png \
    Images/DefaultIcon/MD-tv.png \
    Images/DefaultIcon/MD-vhs.png \
    Images/DefaultIcon/MD-video.png \
    Images/DefaultIcon/MD-vinyl-33-1-3.png \
    Images/DefaultIcon/MD-vinyl-45.png \
    Images/DefaultIcon/MD-volume-0-alt.png \
    Images/DefaultIcon/MD-volume-0.png \
    Images/DefaultIcon/MD-volume-1.png \
    Images/DefaultIcon/MD-volume-2.png \
    Images/DefaultIcon/MD-volume-3.png \
    Images/DefaultIcon/MD-volume-down.png \
    Images/DefaultIcon/MD-volume-up.png \
    Images/DefaultIcon/about.png \
    Images/DefaultIcon/access.png \
    Images/DefaultIcon/activity.png \
    Images/DefaultIcon/add.png \
    Images/DefaultIcon/address-book.png \
    Images/DefaultIcon/airport.png \
    Images/DefaultIcon/alarm.png \
    Images/DefaultIcon/alert-alt.png \
    Images/DefaultIcon/alert.png \
    Images/DefaultIcon/alt.png \
    Images/DefaultIcon/anchor.png \
    Images/DefaultIcon/announce.png \
    Images/DefaultIcon/antivirus-alt.png \
    Images/DefaultIcon/antivirus.png \
    Images/DefaultIcon/arrow-1-backward.png \
    Images/DefaultIcon/arrow-1-down-left.png \
    Images/DefaultIcon/arrow-1-down-right.png \
    Images/DefaultIcon/arrow-1-down.png \
    Images/DefaultIcon/arrow-1-forward.png \
    Images/DefaultIcon/arrow-1-left.png \
    Images/DefaultIcon/arrow-1-right.png \
    Images/DefaultIcon/arrow-1-up-left.png \
    Images/DefaultIcon/arrow-1-up-right.png \
    Images/DefaultIcon/arrow-1-up.png \
    Images/DefaultIcon/arrow-2-down-left.png \
    Images/DefaultIcon/arrow-2-down-right.png \
    Images/DefaultIcon/arrow-2-down.png \
    Images/DefaultIcon/arrow-2-left.png \
    Images/DefaultIcon/arrow-2-right.png \
    Images/DefaultIcon/arrow-2-up-left.png \
    Images/DefaultIcon/arrow-2-up-right.png \
    Images/DefaultIcon/arrow-2-up.png \
    Images/DefaultIcon/arrow-3-down-left.png \
    Images/DefaultIcon/arrow-3-down-right.png \
    Images/DefaultIcon/arrow-3-down.png \
    Images/DefaultIcon/arrow-3-left.png \
    Images/DefaultIcon/arrow-3-right.png \
    Images/DefaultIcon/arrow-3-up-left.png \
    Images/DefaultIcon/arrow-3-up-right.png \
    Images/DefaultIcon/arrow-3-up.png \
    Images/DefaultIcon/arrow-4-down-left.png \
    Images/DefaultIcon/arrow-4-down-right.png \
    Images/DefaultIcon/arrow-4-down.png \
    Images/DefaultIcon/arrow-4-left.png \
    Images/DefaultIcon/arrow-4-right.png \
    Images/DefaultIcon/arrow-4-up-left.png \
    Images/DefaultIcon/arrow-4-up-right.png \
    Images/DefaultIcon/arrow-4-up.png \
    Images/DefaultIcon/arrow-5-down.png \
    Images/DefaultIcon/arrow-5-left.png \
    Images/DefaultIcon/arrow-5-right.png \
    Images/DefaultIcon/arrow-5-up.png \
    Images/DefaultIcon/arrow-6-down.png \
    Images/DefaultIcon/arrow-6-left.png \
    Images/DefaultIcon/arrow-6-right.png \
    Images/DefaultIcon/arrow-6-up.png \
    Images/DefaultIcon/arrow-7-down.png \
    Images/DefaultIcon/arrow-7-left.png \
    Images/DefaultIcon/arrow-7-right.png \
    Images/DefaultIcon/arrow-7-up.png \
    Images/DefaultIcon/arrow-8-down.png \
    Images/DefaultIcon/arrow-8-left.png \
    Images/DefaultIcon/arrow-8-right.png \
    Images/DefaultIcon/arrow-8-up.png \
    Images/DefaultIcon/arrow-circular-alt-1.png \
    Images/DefaultIcon/arrow-circular-alt-2.png \
    Images/DefaultIcon/arrow-orthogonal-alt-1.png \
    Images/DefaultIcon/arrow-orthogonal-alt-2.png \
    Images/DefaultIcon/asterisk-alt.png \
    Images/DefaultIcon/asterisk.png \
    Images/DefaultIcon/attachment.png \
    Images/DefaultIcon/axis-x-y-alt.png \
    Images/DefaultIcon/axis-x-y.png \
    Images/DefaultIcon/badge.png \
    Images/DefaultIcon/bag-alt-1.png \
    Images/DefaultIcon/bag-alt-2.png \
    Images/DefaultIcon/bag-alt-3.png \
    Images/DefaultIcon/bag-alt-4.png \
    Images/DefaultIcon/bag-alt-5.png \
    Images/DefaultIcon/bag.png \
    Images/DefaultIcon/baggage.png \
    Images/DefaultIcon/balance.png \
    Images/DefaultIcon/bank-alt-1.png \
    Images/DefaultIcon/bank-alt-2.png \
    Images/DefaultIcon/bank.png \
    Images/DefaultIcon/barcode.png \
    Images/DefaultIcon/basket-alt-1.png \
    Images/DefaultIcon/basket-alt-2.png \
    Images/DefaultIcon/basket-alt-3.png \
    Images/DefaultIcon/basket.png \
    Images/DefaultIcon/battery-empty-alt.png \
    Images/DefaultIcon/battery-empty.png \
    Images/DefaultIcon/battery-full-alt.png \
    Images/DefaultIcon/battery-full.png \
    Images/DefaultIcon/bicycle.png \
    Images/DefaultIcon/blog.png \
    Images/DefaultIcon/bluetooth.png \
    Images/DefaultIcon/book-alt-2.png \
    Images/DefaultIcon/book-alt-3.png \
    Images/DefaultIcon/book-alt-4.png \
    Images/DefaultIcon/book-alt.png \
    Images/DefaultIcon/book.png \
    Images/DefaultIcon/bookmark-alt.png \
    Images/DefaultIcon/bookmark.png \
    Images/DefaultIcon/books.png \
    Images/DefaultIcon/box-alt.png \
    Images/DefaultIcon/box.png \
    Images/DefaultIcon/briefcase.png \
    Images/DefaultIcon/brush-alt-1.png \
    Images/DefaultIcon/brush-alt-2.png \
    Images/DefaultIcon/brush.png \
    Images/DefaultIcon/bug.png \
    Images/DefaultIcon/bussiness-card.png \
    Images/DefaultIcon/cake-alt.png \
    Images/DefaultIcon/cake.png \
    Images/DefaultIcon/calculator-alt.png \
    Images/DefaultIcon/calculator.png \
    Images/DefaultIcon/calendar-alt-1.png \
    Images/DefaultIcon/calendar-alt-2.png \
    Images/DefaultIcon/calendar.png \
    Images/DefaultIcon/cancel.png \
    Images/DefaultIcon/cart-alt-1.png \
    Images/DefaultIcon/cart-alt-2.png \
    Images/DefaultIcon/cart-alt-3.png \
    Images/DefaultIcon/cart-alt-4.png \
    Images/DefaultIcon/cart-alt-5.png \
    Images/DefaultIcon/cart-alt-6.png \
    Images/DefaultIcon/cart.png \
    Images/DefaultIcon/chair-alt.png \
    Images/DefaultIcon/chair.png \
    Images/DefaultIcon/chat-active-alt-1.png \
    Images/DefaultIcon/chat-active-alt-2.png \
    Images/DefaultIcon/chat-active.png \
    Images/DefaultIcon/chat-alt-1.png \
    Images/DefaultIcon/chat-alt-2.png \
    Images/DefaultIcon/chat-alt-3.png \
    Images/DefaultIcon/chat.png \
    Images/DefaultIcon/check-alt.png \
    Images/DefaultIcon/check.png \
    Images/DefaultIcon/checkbox-empty.png \
    Images/DefaultIcon/checkbox.png \
    Images/DefaultIcon/cheque.png \
    Images/DefaultIcon/cinema.png \
    Images/DefaultIcon/city.png \
    Images/DefaultIcon/code.png \
    Images/DefaultIcon/color-picker.png \
    Images/DefaultIcon/color-swatch.png \
    Images/DefaultIcon/comment-alt.png \
    Images/DefaultIcon/comment.png \
    Images/DefaultIcon/compass-alt.png \
    Images/DefaultIcon/compass.png \
    Images/DefaultIcon/compress.png \
    Images/DefaultIcon/computer-laptop.png \
    Images/DefaultIcon/computer-retro.png \
    Images/DefaultIcon/computer.png \
    Images/DefaultIcon/connect-alt-1.png \
    Images/DefaultIcon/connect-alt-2.png \
    Images/DefaultIcon/connect.png \
    Images/DefaultIcon/connection-error-alt-1.png \
    Images/DefaultIcon/connection-error-alt-2.png \
    Images/DefaultIcon/connection-error.png \
    Images/DefaultIcon/construction.png \
    Images/DefaultIcon/content.png \
    Images/DefaultIcon/controls-alt-1.png \
    Images/DefaultIcon/controls-alt-2.png \
    Images/DefaultIcon/controls.png \
    Images/DefaultIcon/copy.png \
    Images/DefaultIcon/couch-alt-1.png \
    Images/DefaultIcon/couch-alt-2.png \
    Images/DefaultIcon/couch.png \
    Images/DefaultIcon/counter.png \
    Images/DefaultIcon/credit-card.png \
    Images/DefaultIcon/crop.png \
    Images/DefaultIcon/cross.png \
    Images/DefaultIcon/cup-alt.png \
    Images/DefaultIcon/cup.png \
    Images/DefaultIcon/cut.png \
    Images/DefaultIcon/data-alt-1.png \
    Images/DefaultIcon/data-alt-2.png \
    Images/DefaultIcon/data.png \
    Images/DefaultIcon/database-add-alt-1.png \
    Images/DefaultIcon/database-add-alt-2.png \
    Images/DefaultIcon/database-add.png \
    Images/DefaultIcon/database-alt-1.png \
    Images/DefaultIcon/database-alt-2.png \
    Images/DefaultIcon/database-download-alt-1.png \
    Images/DefaultIcon/database-download-alt-2.png \
    Images/DefaultIcon/database-download.png \
    Images/DefaultIcon/database-reload-alt-1.png \
    Images/DefaultIcon/database-reload-alt-2.png \
    Images/DefaultIcon/database-reload.png \
    Images/DefaultIcon/database-remove-alt-1.png \
    Images/DefaultIcon/database-remove-alt-2.png \
    Images/DefaultIcon/database-remove.png \
    Images/DefaultIcon/database-upload-alt-1.png \
    Images/DefaultIcon/database-upload-alt-2.png \
    Images/DefaultIcon/database-upload.png \
    Images/DefaultIcon/database-user-alt.png \
    Images/DefaultIcon/database-user.png \
    Images/DefaultIcon/database.png \
    Images/DefaultIcon/delete.png \
    Images/DefaultIcon/directions-alt.png \
    Images/DefaultIcon/directions.png \
    Images/DefaultIcon/display-mac-alt.png \
    Images/DefaultIcon/display-mac.png \
    Images/DefaultIcon/display.png \
    Images/DefaultIcon/document-empty.png \
    Images/DefaultIcon/document-new.png \
    Images/DefaultIcon/document.png \
    Images/DefaultIcon/documents.png \
    Images/DefaultIcon/door-closed.png \
    Images/DefaultIcon/door.png \
    Images/DefaultIcon/download-alt-1.png \
    Images/DefaultIcon/download-alt-2.png \
    Images/DefaultIcon/download-alt-3.png \
    Images/DefaultIcon/download-alt-4.png \
    Images/DefaultIcon/download.png \
    Images/DefaultIcon/drawer-locked.png \
    Images/DefaultIcon/drawer-unlocked.png \
    Images/DefaultIcon/drawer.png \
    Images/DefaultIcon/drawers-alt-1.png \
    Images/DefaultIcon/drawers-alt-2.png \
    Images/DefaultIcon/drawers.png \
    Images/DefaultIcon/drill.png \
    Images/DefaultIcon/drive-disk-cd.png \
    Images/DefaultIcon/drive-network.png \
    Images/DefaultIcon/edit-alt-1.png \
    Images/DefaultIcon/edit-alt-2.png \
    Images/DefaultIcon/edit-document.png \
    Images/DefaultIcon/edit.png \
    Images/DefaultIcon/eightball.png \
    Images/DefaultIcon/elevator.png \
    Images/DefaultIcon/enter.png \
    Images/DefaultIcon/eraser.png \
    Images/DefaultIcon/ethernet.png \
    Images/DefaultIcon/export.png \
    Images/DefaultIcon/facebook-alt.png \
    Images/DefaultIcon/facebook.png \
    Images/DefaultIcon/factory.png \
    Images/DefaultIcon/fan-alt.png \
    Images/DefaultIcon/fan.png \
    Images/DefaultIcon/favourite-add.png \
    Images/DefaultIcon/favourite.png \
    Images/DefaultIcon/file-add.png \
    Images/DefaultIcon/file-download-alt.png \
    Images/DefaultIcon/file-download.png \
    Images/DefaultIcon/file-edit.png \
    Images/DefaultIcon/file-remove.png \
    Images/DefaultIcon/file-upload-alt.png \
    Images/DefaultIcon/file-upload.png \
    Images/DefaultIcon/file.png \
    Images/DefaultIcon/files.png \
    Images/DefaultIcon/fill.png \
    Images/DefaultIcon/filter.png \
    Images/DefaultIcon/find.png \
    Images/DefaultIcon/fire.png \
    Images/DefaultIcon/firewall.png \
    Images/DefaultIcon/firewire.png \
    Images/DefaultIcon/first-aid-alt.png \
    Images/DefaultIcon/first-aid.png \
    Images/DefaultIcon/flag.png \
    Images/DefaultIcon/folder-open.png \
    Images/DefaultIcon/folder.png \
    Images/DefaultIcon/font.png \
    Images/DefaultIcon/food.png \
    Images/DefaultIcon/ftp-alt-1.png \
    Images/DefaultIcon/ftp-alt-2.png \
    Images/DefaultIcon/ftp.png \
    Images/DefaultIcon/full-screen-alt-1.png \
    Images/DefaultIcon/full-screen-alt-2.png \
    Images/DefaultIcon/full-screen-alt-3.png \
    Images/DefaultIcon/full-screen-alt-4.png \
    Images/DefaultIcon/full-screen-alt-5.png \
    Images/DefaultIcon/full-screen-exit-alt-1.png \
    Images/DefaultIcon/full-screen-exit-alt-2.png \
    Images/DefaultIcon/full-screen-exit-alt-3.png \
    Images/DefaultIcon/full-screen-exit-alt-4.png \
    Images/DefaultIcon/full-screen-exit-alt-5.png \
    Images/DefaultIcon/full-screen-exit.png \
    Images/DefaultIcon/full-screen.png \
    Images/DefaultIcon/gameboy.png \
    Images/DefaultIcon/games-alt-1.png \
    Images/DefaultIcon/games-alt-2.png \
    Images/DefaultIcon/games-alt-3.png \
    Images/DefaultIcon/games-alt-4.png \
    Images/DefaultIcon/games-alt-5.png \
    Images/DefaultIcon/games-alt-6.png \
    Images/DefaultIcon/games.png \
    Images/DefaultIcon/gift.png \
    Images/DefaultIcon/glasses-swim.png \
    Images/DefaultIcon/glasses.png \
    Images/DefaultIcon/grid-alt-1.png \
    Images/DefaultIcon/grid-alt-2.png \
    Images/DefaultIcon/grid-alt-3.png \
    Images/DefaultIcon/grid-dot.png \
    Images/DefaultIcon/grid.png \
    Images/DefaultIcon/hammer-alt.png \
    Images/DefaultIcon/hammer.png \
    Images/DefaultIcon/hardware-chip.png \
    Images/DefaultIcon/hardware-processor.png \
    Images/DefaultIcon/hedge.png \
    Images/DefaultIcon/help-alt.png \
    Images/DefaultIcon/help.png \
    Images/DefaultIcon/hierarchy.png \
    Images/DefaultIcon/high-definition.png \
    Images/DefaultIcon/home.png \
    Images/DefaultIcon/i-phone.png \
    Images/DefaultIcon/i-pod.png \
    Images/DefaultIcon/icecream.png \
    Images/DefaultIcon/idea-alt.png \
    Images/DefaultIcon/idea.png \
    Images/DefaultIcon/info.png \
    Images/DefaultIcon/key-A.png \
    Images/DefaultIcon/key-Alt.png \
    Images/DefaultIcon/key-apple.png \
    Images/DefaultIcon/key-backspace-alt.png \
    Images/DefaultIcon/key-backspace.png \
    Images/DefaultIcon/key-caps.png \
    Images/DefaultIcon/key-command.png \
    Images/DefaultIcon/key-control.png \
    Images/DefaultIcon/key-enter.png \
    Images/DefaultIcon/key-option.png \
    Images/DefaultIcon/key-page-down.png \
    Images/DefaultIcon/key-page-up.png \
    Images/DefaultIcon/key-shift.png \
    Images/DefaultIcon/key-tab.png \
    Images/DefaultIcon/key-windows.png \
    Images/DefaultIcon/key.png \
    Images/DefaultIcon/keyboard.png \
    Images/DefaultIcon/keyhole.png \
    Images/DefaultIcon/kokoretsi.png \
    Images/DefaultIcon/kraftwerk.png \
    Images/DefaultIcon/label.png \
    Images/DefaultIcon/lamp-alt-1.png \
    Images/DefaultIcon/lamp-alt-2.png \
    Images/DefaultIcon/lamp.png \
    Images/DefaultIcon/layers.png \
    Images/DefaultIcon/layout-content.png \
    Images/DefaultIcon/layout-header.png \
    Images/DefaultIcon/layout-sidebar.png \
    Images/DefaultIcon/layout.png \
    Images/DefaultIcon/license-key.png \
    Images/DefaultIcon/link-broken.png \
    Images/DefaultIcon/link.png \
    Images/DefaultIcon/list-numbered.png \
    Images/DefaultIcon/list-ordered.png \
    Images/DefaultIcon/list-unordered.png \
    Images/DefaultIcon/list.png \
    Images/DefaultIcon/location.png \
    Images/DefaultIcon/login.png \
    Images/DefaultIcon/logout.png \
    Images/DefaultIcon/luck.png \
    Images/DefaultIcon/magnet.png \
    Images/DefaultIcon/mail-inbox.png \
    Images/DefaultIcon/mail-read.png \
    Images/DefaultIcon/mail-sent.png \
    Images/DefaultIcon/mail.png \
    Images/DefaultIcon/man.png \
    Images/DefaultIcon/map-marker-pin.png \
    Images/DefaultIcon/map.png \
    Images/DefaultIcon/medal-alt.png \
    Images/DefaultIcon/medal.png \
    Images/DefaultIcon/mobile-alt.png \
    Images/DefaultIcon/mobile.png \
    Images/DefaultIcon/module.png \
    Images/DefaultIcon/moleskine.png \
    Images/DefaultIcon/moon.png \
    Images/DefaultIcon/mouse.png \
    Images/DefaultIcon/navigation-alt-1.png \
    Images/DefaultIcon/navigation-alt-2.png \
    Images/DefaultIcon/navigation.png \
    Images/DefaultIcon/network-alt-1.png \
    Images/DefaultIcon/network.png \
    Images/DefaultIcon/no.png \
    Images/DefaultIcon/node.png \
    Images/DefaultIcon/notepad-alt.png \
    Images/DefaultIcon/notepad.png \
    Images/DefaultIcon/open-in-new-window.png \
    Images/DefaultIcon/open-source.png \
    Images/DefaultIcon/orientation-landscape.png \
    Images/DefaultIcon/orientation-portrait.png \
    Images/DefaultIcon/padlock-closed.png \
    Images/DefaultIcon/padlock-open.png \
    Images/DefaultIcon/paintroller-alt.png \
    Images/DefaultIcon/paintroller.png \
    Images/DefaultIcon/park-bench.png \
    Images/DefaultIcon/paste.png \
    Images/DefaultIcon/pattern.png \
    Images/DefaultIcon/pen.png \
    Images/DefaultIcon/pill.png \
    Images/DefaultIcon/pinetree.png \
    Images/DefaultIcon/plugin-disabled.png \
    Images/DefaultIcon/plugin.png \
    Images/DefaultIcon/podcast.png \
    Images/DefaultIcon/pollution.png \
    Images/DefaultIcon/power-off.png \
    Images/DefaultIcon/power-on-off.png \
    Images/DefaultIcon/power-on.png \
    Images/DefaultIcon/power-standby.png \
    Images/DefaultIcon/preferences.png \
    Images/DefaultIcon/presentation.png \
    Images/DefaultIcon/print-alt.png \
    Images/DefaultIcon/print.png \
    Images/DefaultIcon/printer-preview.png \
    Images/DefaultIcon/printer.png \
    Images/DefaultIcon/projector.png \
    Images/DefaultIcon/read-only.png \
    Images/DefaultIcon/refreshment.png \
    Images/DefaultIcon/register.png \
    Images/DefaultIcon/remote-control.png \
    Images/DefaultIcon/report.png \
    Images/DefaultIcon/resize.png \
    Images/DefaultIcon/rip.png \
    Images/DefaultIcon/road-sign.png \
    Images/DefaultIcon/rss.png \
    Images/DefaultIcon/ruby.png \
    Images/DefaultIcon/ruler-alt.png \
    Images/DefaultIcon/ruler.png \
    Images/DefaultIcon/safety-box.png \
    Images/DefaultIcon/save.png \
    Images/DefaultIcon/science.png \
    Images/DefaultIcon/screenshot.png \
    Images/DefaultIcon/script.png \
    Images/DefaultIcon/search-advanced.png \
    Images/DefaultIcon/search.png \
    Images/DefaultIcon/server.png \
    Images/DefaultIcon/servers.png \
    Images/DefaultIcon/settings.png \
    Images/DefaultIcon/shape-circle.png \
    Images/DefaultIcon/shape-ellipse.png \
    Images/DefaultIcon/shape-hexagon.png \
    Images/DefaultIcon/shape-kite.png \
    Images/DefaultIcon/shape-parallelogram-orthogonal.png \
    Images/DefaultIcon/shape-pentagon.png \
    Images/DefaultIcon/shape-rhombus.png \
    Images/DefaultIcon/shape-square.png \
    Images/DefaultIcon/shape-trapezoid.png \
    Images/DefaultIcon/shape-triangle-equilateral.png \
    Images/DefaultIcon/shape-triangle-isosceles.png \
    Images/DefaultIcon/shape-triangle-rectangular.png \
    Images/DefaultIcon/shape-triangle-scalene.png \
    Images/DefaultIcon/shapes-align-hori-center.png \
    Images/DefaultIcon/shapes-align-hori-left.png \
    Images/DefaultIcon/shapes-align-hori-right.png \
    Images/DefaultIcon/shapes-align-verti-bottom.png \
    Images/DefaultIcon/shapes-align-verti-middle.png \
    Images/DefaultIcon/shapes-align-verti-top.png \
    Images/DefaultIcon/shapes-flip-horizontal.png \
    Images/DefaultIcon/shapes-flip-vertical.png \
    Images/DefaultIcon/shapes-move-back.png \
    Images/DefaultIcon/shapes-move-backward.png \
    Images/DefaultIcon/shapes-move-forward.png \
    Images/DefaultIcon/shapes-move-front.png \
    Images/DefaultIcon/shapes-rotate-anticlockwise.png \
    Images/DefaultIcon/shapes-rotate-clockwise.png \
    Images/DefaultIcon/sitemap.png \
    Images/DefaultIcon/spaceship.png \
    Images/DefaultIcon/stamp.png \
    Images/DefaultIcon/star.png \
    Images/DefaultIcon/statistics-chart.png \
    Images/DefaultIcon/statistics-pie-chart.png \
    Images/DefaultIcon/sticky-note.png \
    Images/DefaultIcon/stop-alt.png \
    Images/DefaultIcon/stop.png \
    Images/DefaultIcon/stopwatch.png \
    Images/DefaultIcon/store.png \
    Images/DefaultIcon/switch-off-alt.png \
    Images/DefaultIcon/switch-off.png \
    Images/DefaultIcon/switch-on-alt.png \
    Images/DefaultIcon/switch-on.png \
    Images/DefaultIcon/tab.png \
    Images/DefaultIcon/table.png \
    Images/DefaultIcon/tag.png \
    Images/DefaultIcon/tags.png \
    Images/DefaultIcon/target.png \
    Images/DefaultIcon/telephone.png \
    Images/DefaultIcon/tent.png \
    Images/DefaultIcon/terminal.png \
    Images/DefaultIcon/thumbnails.png \
    Images/DefaultIcon/tie.png \
    Images/DefaultIcon/time-alt.png \
    Images/DefaultIcon/time.png \
    Images/DefaultIcon/toolbox.png \
    Images/DefaultIcon/trafficlight-green.png \
    Images/DefaultIcon/trafficlight-orange.png \
    Images/DefaultIcon/trafficlight-red.png \
    Images/DefaultIcon/trafficlight.png \
    Images/DefaultIcon/trash-empty.png \
    Images/DefaultIcon/trash-full.png \
    Images/DefaultIcon/trophy.png \
    Images/DefaultIcon/truck.png \
    Images/DefaultIcon/twitter.png \
    Images/DefaultIcon/typewritter.png \
    Images/DefaultIcon/unfold-from-bottom.png \
    Images/DefaultIcon/unfold-from-left.png \
    Images/DefaultIcon/unfold-from-right.png \
    Images/DefaultIcon/unfold-from-top.png \
    Images/DefaultIcon/unfold-multiple.png \
    Images/DefaultIcon/user-alt-1.png \
    Images/DefaultIcon/user-alt-2.png \
    Images/DefaultIcon/user-alt-3.png \
    Images/DefaultIcon/user-alt-4.png \
    Images/DefaultIcon/user-art.png \
    Images/DefaultIcon/user-chat.png \
    Images/DefaultIcon/user-female-alt-1.png \
    Images/DefaultIcon/user-female-alt-2.png \
    Images/DefaultIcon/user-female.png \
    Images/DefaultIcon/user-locked.png \
    Images/DefaultIcon/user-male-alt-1.png \
    Images/DefaultIcon/user-male-alt-2.png \
    Images/DefaultIcon/user-male-alt-3.png \
    Images/DefaultIcon/user-male.png \
    Images/DefaultIcon/user-offline.png \
    Images/DefaultIcon/user-refresh.png \
    Images/DefaultIcon/user-sleep.png \
    Images/DefaultIcon/user.png \
    Images/DefaultIcon/users-alt.png \
    Images/DefaultIcon/users.png \
    Images/DefaultIcon/view.png \
    Images/DefaultIcon/wall-alt.png \
    Images/DefaultIcon/wall.png \
    Images/DefaultIcon/wallet.png \
    Images/DefaultIcon/water-alt.png \
    Images/DefaultIcon/water.png \
    Images/DefaultIcon/weather-cloud-sun.png \
    Images/DefaultIcon/weather-cloud.png \
    Images/DefaultIcon/weather-clouds.png \
    Images/DefaultIcon/weather-rain.png \
    Images/DefaultIcon/weather-snow.png \
    Images/DefaultIcon/weather-sun.png \
    Images/DefaultIcon/weather-thunder.png \
    Images/DefaultIcon/web.png \
    Images/DefaultIcon/weight.png \
    Images/DefaultIcon/wi-fi.png \
    Images/DefaultIcon/window-stack.png \
    Images/DefaultIcon/window-tile-horizontally.png \
    Images/DefaultIcon/window-tile-vertically.png \
    Images/DefaultIcon/window-tile.png \
    Images/DefaultIcon/window.png \
    Images/DefaultIcon/wireless-router.png \
    Images/DefaultIcon/wizard.png \
    Images/DefaultIcon/zoom-in.png \
    Images/DefaultIcon/zoom-out.png \
    Images/DefaultIcon/zoom.png

RESOURCES += \
    resources.qrc
